export { default as Brands } from './Brands';
export { default as Favourite } from './Favourites';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as MobileApp } from './MobileApp';
export { default as Navbar } from './Navbar';
export { default as NewArrivals } from './NewArrivals';
export { default as Sale } from './Sale';
export { default as Subscribe } from './Subscribe';
